import React from "react";
import type { Metadata } from "next";
import "@shared/styles/global.scss";
import { PopupProvider } from "@shared/lib/context/PopupContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <PopupProvider>
          <div className="container">{children}</div>
        </PopupProvider>
      </body>
    </html>
  );
}
